platform :ios, '10.0'

target 'Weather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Weather
    pod 'SwiftyJSON'
    pod 'Alamofire'
    pod 'SVProgressHUD'

end
